/**
 * 第七次全国人口普查 (2020) 数据模块
 * 数据来源：国家统计局第七次全国人口普查公报
 *
 * 核心结构：
 *   7大区 → 省份 → 城市（省会/特大/地级/县级行政区）→ 街道/乡镇 → 年龄性别分层人口
 */

// ─────────────────────────────────────────────
// 1. 七大地理区域（按地理 + 饮食习惯划分）
// ─────────────────────────────────────────────
const REGIONS = [
  {
    id: 1,
    name: '华北区',
    desc: '北方面食文化区',
    color: '#4e79a7',
    provinces: ['京', '津', '冀', '晋', '蒙']
  },
  {
    id: 2,
    name: '东北区',
    desc: '东北饮食文化区',
    color: '#f28e2b',
    provinces: ['辽', '吉', '黑']
  },
  {
    id: 3,
    name: '华东区',
    desc: '江南精细饮食区',
    color: '#e15759',
    provinces: ['沪', '苏', '浙', '皖', '闽', '赣', '鲁']
  },
  {
    id: 4,
    name: '华中区',
    desc: '中原饮食文化区',
    color: '#76b7b2',
    provinces: ['豫', '鄂', '湘']
  },
  {
    id: 5,
    name: '华南区',
    desc: '粤系饮食文化区',
    color: '#59a14f',
    provinces: ['粤', '桂', '琼']
  },
  {
    id: 6,
    name: '西南区',
    desc: '川渝辣味饮食区',
    color: '#edc948',
    provinces: ['渝', '川', '黔', '滇', '藏']
  },
  {
    id: 7,
    name: '西北区',
    desc: '西北清真饮食区',
    color: '#b07aa1',
    provinces: ['陕', '甘', '青', '宁', '新']
  }
];

// ─────────────────────────────────────────────
// 2. 省份数据（七普真实人口数据）
//    type: capital=省会/直辖市  mega=特大城市  city=地级市  county=县级行政区
// ─────────────────────────────────────────────
const PROVINCES = {
  // 华北区
  '京': { name: '北京市',   region: 1, pop: 21893095,  capital: '北京市', abbr: '京' },
  '津': { name: '天津市',   region: 1, pop: 13866009,  capital: '天津市', abbr: '津' },
  '冀': { name: '河北省',   region: 1, pop: 74610235,  capital: '石家庄市', abbr: '冀' },
  '晋': { name: '山西省',   region: 1, pop: 34915616,  capital: '太原市', abbr: '晋' },
  '蒙': { name: '内蒙古自治区', region: 1, pop: 24049155, capital: '呼和浩特市', abbr: '蒙' },
  // 东北区
  '辽': { name: '辽宁省',   region: 2, pop: 42591407,  capital: '沈阳市', abbr: '辽' },
  '吉': { name: '吉林省',   region: 2, pop: 24073453,  capital: '长春市', abbr: '吉' },
  '黑': { name: '黑龙江省', region: 2, pop: 31850088,  capital: '哈尔滨市', abbr: '黑' },
  // 华东区
  '沪': { name: '上海市',   region: 3, pop: 24870895,  capital: '上海市', abbr: '沪' },
  '苏': { name: '江苏省',   region: 3, pop: 84748016,  capital: '南京市', abbr: '苏' },
  '浙': { name: '浙江省',   region: 3, pop: 64567588,  capital: '杭州市', abbr: '浙' },
  '皖': { name: '安徽省',   region: 3, pop: 61027171,  capital: '合肥市', abbr: '皖' },
  '闽': { name: '福建省',   region: 3, pop: 41540086,  capital: '福州市', abbr: '闽' },
  '赣': { name: '江西省',   region: 3, pop: 45188635,  capital: '南昌市', abbr: '赣' },
  '鲁': { name: '山东省',   region: 3, pop: 101527453, capital: '济南市', abbr: '鲁' },
  // 华中区
  '豫': { name: '河南省',   region: 4, pop: 99365519,  capital: '郑州市', abbr: '豫' },
  '鄂': { name: '湖北省',   region: 4, pop: 57752557,  capital: '武汉市', abbr: '鄂' },
  '湘': { name: '湖南省',   region: 4, pop: 66444864,  capital: '长沙市', abbr: '湘' },
  // 华南区
  '粤': { name: '广东省',   region: 5, pop: 126012510, capital: '广州市', abbr: '粤' },
  '桂': { name: '广西壮族自治区', region: 5, pop: 50126804, capital: '南宁市', abbr: '桂' },
  '琼': { name: '海南省',   region: 5, pop: 10081232,  capital: '海口市', abbr: '琼' },
  // 西南区
  '渝': { name: '重庆市',   region: 6, pop: 32054159,  capital: '重庆市', abbr: '渝' },
  '川': { name: '四川省',   region: 6, pop: 83674866,  capital: '成都市', abbr: '川' },
  '黔': { name: '贵州省',   region: 6, pop: 38562148,  capital: '贵阳市', abbr: '黔' },
  '滇': { name: '云南省',   region: 6, pop: 47209277,  capital: '昆明市', abbr: '滇' },
  '藏': { name: '西藏自治区', region: 6, pop: 3648100,  capital: '拉萨市', abbr: '藏' },
  // 西北区
  '陕': { name: '陕西省',   region: 7, pop: 39528999,  capital: '西安市', abbr: '陕' },
  '甘': { name: '甘肃省',   region: 7, pop: 25019831,  capital: '兰州市', abbr: '甘' },
  '青': { name: '青海省',   region: 7, pop: 5923957,   capital: '西宁市', abbr: '青' },
  '宁': { name: '宁夏回族自治区', region: 7, pop: 7202654, capital: '银川市', abbr: '宁' },
  '新': { name: '新疆维吾尔自治区', region: 7, pop: 25852345, capital: '乌鲁木齐市', abbr: '新' },
};

// ─────────────────────────────────────────────
// 城市数据：每省所有城市（来自Excel真实区划数据，2024版）
// type: capital=省会/直辖市  mega=特大城市  city=地级市  county=县级行政区
// ─────────────────────────────────────────────
const CITIES = {
  '京': [
    { name: '市辖区', type: 'capital', pop: 10000000 },
    { name: '门头沟区', type: 'county', pop: 200000 },
    { name: '房山区', type: 'county', pop: 200000 },
    { name: '通州区', type: 'county', pop: 200000 },
    { name: '顺义区', type: 'county', pop: 200000 },
    { name: '昌平区', type: 'county', pop: 200000 },
    { name: '大兴区', type: 'county', pop: 200000 },
    { name: '怀柔区', type: 'county', pop: 200000 },
    { name: '平谷区', type: 'county', pop: 200000 },
    { name: '密云区', type: 'county', pop: 200000 },
    { name: '延庆区', type: 'county', pop: 200000 },
  ],
  '津': [
    { name: '市辖区', type: 'capital', pop: 10000000 },
    { name: '武清区', type: 'county', pop: 200000 },
    { name: '宝坻区', type: 'county', pop: 200000 },
    { name: '宁河区', type: 'county', pop: 200000 },
    { name: '静海区', type: 'county', pop: 200000 },
    { name: '蓟州区', type: 'county', pop: 200000 },
  ],
  '冀': [
    { name: '石家庄市', type: 'capital', pop: 10000000 },
    { name: '唐山市', type: 'city', pop: 3000000 },
    { name: '秦皇岛市', type: 'city', pop: 3000000 },
    { name: '邯郸市', type: 'city', pop: 3000000 },
    { name: '邢台市', type: 'city', pop: 3000000 },
    { name: '井陉县', type: 'county', pop: 200000 },
    { name: '正定县', type: 'county', pop: 200000 },
    { name: '行唐县', type: 'county', pop: 200000 },
    { name: '灵寿县', type: 'county', pop: 200000 },
    { name: '高邑县', type: 'county', pop: 200000 },
    { name: '深泽县', type: 'county', pop: 200000 },
    { name: '赞皇县', type: 'county', pop: 200000 },
    { name: '无极县', type: 'county', pop: 200000 },
    { name: '平山县', type: 'county', pop: 200000 },
    { name: '元氏县', type: 'county', pop: 200000 },
    { name: '赵县', type: 'county', pop: 200000 },
    { name: '辛集市', type: 'county', pop: 200000 },
    { name: '晋州市', type: 'county', pop: 200000 },
    { name: '新乐市', type: 'county', pop: 200000 },
    { name: '滦南县', type: 'county', pop: 200000 },
    { name: '乐亭县', type: 'county', pop: 200000 },
    { name: '迁西县', type: 'county', pop: 200000 },
    { name: '玉田县', type: 'county', pop: 200000 },
    { name: '遵化市', type: 'county', pop: 200000 },
    { name: '迁安市', type: 'county', pop: 200000 },
  ],
  '晋': [
    { name: '太原市', type: 'capital', pop: 10000000 },
    { name: '大同市', type: 'city', pop: 3000000 },
    { name: '阳泉市', type: 'city', pop: 3000000 },
    { name: '长治市', type: 'city', pop: 3000000 },
    { name: '晋城市', type: 'city', pop: 3000000 },
    { name: '清徐县', type: 'county', pop: 200000 },
    { name: '阳曲县', type: 'county', pop: 200000 },
    { name: '娄烦县', type: 'county', pop: 200000 },
    { name: '古交市', type: 'county', pop: 200000 },
    { name: '阳高县', type: 'county', pop: 200000 },
    { name: '天镇县', type: 'county', pop: 200000 },
    { name: '广灵县', type: 'county', pop: 200000 },
    { name: '灵丘县', type: 'county', pop: 200000 },
    { name: '浑源县', type: 'county', pop: 200000 },
    { name: '左云县', type: 'county', pop: 200000 },
    { name: '平定县', type: 'county', pop: 200000 },
    { name: '盂县', type: 'county', pop: 200000 },
    { name: '襄垣县', type: 'county', pop: 200000 },
    { name: '平顺县', type: 'county', pop: 200000 },
    { name: '黎城县', type: 'county', pop: 200000 },
    { name: '壶关县', type: 'county', pop: 200000 },
    { name: '长子县', type: 'county', pop: 200000 },
    { name: '武乡县', type: 'county', pop: 200000 },
    { name: '沁县', type: 'county', pop: 200000 },
    { name: '沁源县', type: 'county', pop: 200000 },
  ],
  '蒙': [
    { name: '呼和浩特市', type: 'capital', pop: 10000000 },
    { name: '包头市', type: 'city', pop: 3000000 },
    { name: '乌海市', type: 'city', pop: 3000000 },
    { name: '赤峰市', type: 'city', pop: 3000000 },
    { name: '通辽市', type: 'city', pop: 3000000 },
    { name: '土默特左旗', type: 'county', pop: 200000 },
    { name: '托克托县', type: 'county', pop: 200000 },
    { name: '和林格尔县', type: 'county', pop: 200000 },
    { name: '清水河县', type: 'county', pop: 200000 },
    { name: '武川县', type: 'county', pop: 200000 },
    { name: '土默特右旗', type: 'county', pop: 200000 },
    { name: '固阳县', type: 'county', pop: 200000 },
    { name: '达尔罕茂明安联合旗', type: 'county', pop: 200000 },
    { name: '阿鲁科尔沁旗', type: 'county', pop: 200000 },
    { name: '巴林左旗', type: 'county', pop: 200000 },
    { name: '巴林右旗', type: 'county', pop: 200000 },
    { name: '林西县', type: 'county', pop: 200000 },
    { name: '克什克腾旗', type: 'county', pop: 200000 },
    { name: '翁牛特旗', type: 'county', pop: 200000 },
    { name: '喀喇沁旗', type: 'county', pop: 200000 },
    { name: '宁城县', type: 'county', pop: 200000 },
    { name: '敖汉旗', type: 'county', pop: 200000 },
    { name: '科尔沁左翼中旗', type: 'county', pop: 200000 },
    { name: '科尔沁左翼后旗', type: 'county', pop: 200000 },
    { name: '开鲁县', type: 'county', pop: 200000 },
  ],
  '辽': [
    { name: '沈阳市', type: 'capital', pop: 10000000 },
    { name: '大连市', type: 'city', pop: 3000000 },
    { name: '鞍山市', type: 'city', pop: 3000000 },
    { name: '抚顺市', type: 'city', pop: 3000000 },
    { name: '本溪市', type: 'city', pop: 3000000 },
    { name: '康平县', type: 'county', pop: 200000 },
    { name: '法库县', type: 'county', pop: 200000 },
    { name: '新民市', type: 'county', pop: 200000 },
    { name: '长海县', type: 'county', pop: 200000 },
    { name: '瓦房店市', type: 'county', pop: 200000 },
    { name: '庄河市', type: 'county', pop: 200000 },
    { name: '台安县', type: 'county', pop: 200000 },
    { name: '岫岩满族自治县', type: 'county', pop: 200000 },
    { name: '海城市', type: 'county', pop: 200000 },
    { name: '抚顺县', type: 'county', pop: 200000 },
    { name: '新宾满族自治县', type: 'county', pop: 200000 },
    { name: '清原满族自治县', type: 'county', pop: 200000 },
    { name: '本溪满族自治县', type: 'county', pop: 200000 },
    { name: '桓仁满族自治县', type: 'county', pop: 200000 },
    { name: '宽甸满族自治县', type: 'county', pop: 200000 },
    { name: '东港市', type: 'county', pop: 200000 },
    { name: '凤城市', type: 'county', pop: 200000 },
    { name: '黑山县', type: 'county', pop: 200000 },
    { name: '义县', type: 'county', pop: 200000 },
    { name: '凌海市', type: 'county', pop: 200000 },
  ],
  '吉': [
    { name: '长春市', type: 'capital', pop: 10000000 },
    { name: '吉林市', type: 'city', pop: 3000000 },
    { name: '四平市', type: 'city', pop: 3000000 },
    { name: '辽源市', type: 'city', pop: 3000000 },
    { name: '通化市', type: 'city', pop: 3000000 },
    { name: '农安县', type: 'county', pop: 200000 },
    { name: '榆树市', type: 'county', pop: 200000 },
    { name: '德惠市', type: 'county', pop: 200000 },
    { name: '公主岭市', type: 'county', pop: 200000 },
    { name: '永吉县', type: 'county', pop: 200000 },
    { name: '蛟河市', type: 'county', pop: 200000 },
    { name: '桦甸市', type: 'county', pop: 200000 },
    { name: '舒兰市', type: 'county', pop: 200000 },
    { name: '磐石市', type: 'county', pop: 200000 },
    { name: '梨树县', type: 'county', pop: 200000 },
    { name: '伊通满族自治县', type: 'county', pop: 200000 },
    { name: '双辽市', type: 'county', pop: 200000 },
    { name: '东丰县', type: 'county', pop: 200000 },
    { name: '东辽县', type: 'county', pop: 200000 },
    { name: '通化县', type: 'county', pop: 200000 },
    { name: '辉南县', type: 'county', pop: 200000 },
    { name: '柳河县', type: 'county', pop: 200000 },
    { name: '梅河口市', type: 'county', pop: 200000 },
    { name: '集安市', type: 'county', pop: 200000 },
    { name: '抚松县', type: 'county', pop: 200000 },
  ],
  '黑': [
    { name: '哈尔滨市', type: 'capital', pop: 10000000 },
    { name: '齐齐哈尔市', type: 'city', pop: 3000000 },
    { name: '鸡西市', type: 'city', pop: 3000000 },
    { name: '鹤岗市', type: 'city', pop: 3000000 },
    { name: '双鸭山市', type: 'city', pop: 3000000 },
    { name: '依兰县', type: 'county', pop: 200000 },
    { name: '方正县', type: 'county', pop: 200000 },
    { name: '宾县', type: 'county', pop: 200000 },
    { name: '巴彦县', type: 'county', pop: 200000 },
    { name: '木兰县', type: 'county', pop: 200000 },
    { name: '通河县', type: 'county', pop: 200000 },
    { name: '延寿县', type: 'county', pop: 200000 },
    { name: '尚志市', type: 'county', pop: 200000 },
    { name: '五常市', type: 'county', pop: 200000 },
    { name: '龙江县', type: 'county', pop: 200000 },
    { name: '依安县', type: 'county', pop: 200000 },
    { name: '泰来县', type: 'county', pop: 200000 },
    { name: '甘南县', type: 'county', pop: 200000 },
    { name: '富裕县', type: 'county', pop: 200000 },
    { name: '克山县', type: 'county', pop: 200000 },
    { name: '克东县', type: 'county', pop: 200000 },
    { name: '拜泉县', type: 'county', pop: 200000 },
    { name: '讷河市', type: 'county', pop: 200000 },
    { name: '鸡东县', type: 'county', pop: 200000 },
    { name: '虎林市', type: 'county', pop: 200000 },
  ],
  '沪': [
    { name: '市辖区', type: 'capital', pop: 10000000 },
    { name: '闵行区', type: 'county', pop: 200000 },
    { name: '宝山区', type: 'county', pop: 200000 },
    { name: '嘉定区', type: 'county', pop: 200000 },
    { name: '金山区', type: 'county', pop: 200000 },
    { name: '松江区', type: 'county', pop: 200000 },
    { name: '青浦区', type: 'county', pop: 200000 },
    { name: '奉贤区', type: 'county', pop: 200000 },
    { name: '崇明区', type: 'county', pop: 200000 },
  ],
  '苏': [
    { name: '南京市', type: 'capital', pop: 10000000 },
    { name: '无锡市', type: 'city', pop: 3000000 },
    { name: '徐州市', type: 'city', pop: 3000000 },
    { name: '常州市', type: 'city', pop: 3000000 },
    { name: '苏州市', type: 'mega', pop: 8000000 },
    { name: '江阴市', type: 'county', pop: 200000 },
    { name: '宜兴市', type: 'county', pop: 200000 },
    { name: '丰县', type: 'county', pop: 200000 },
    { name: '沛县', type: 'county', pop: 200000 },
    { name: '睢宁县', type: 'county', pop: 200000 },
    { name: '新沂市', type: 'county', pop: 200000 },
    { name: '邳州市', type: 'county', pop: 200000 },
    { name: '溧阳市', type: 'county', pop: 200000 },
    { name: '常熟市', type: 'county', pop: 200000 },
    { name: '张家港市', type: 'county', pop: 200000 },
    { name: '昆山市', type: 'county', pop: 200000 },
    { name: '太仓市', type: 'county', pop: 200000 },
    { name: '如东县', type: 'county', pop: 200000 },
    { name: '启东市', type: 'county', pop: 200000 },
    { name: '如皋市', type: 'county', pop: 200000 },
    { name: '海安市', type: 'county', pop: 200000 },
    { name: '东海县', type: 'county', pop: 200000 },
    { name: '灌云县', type: 'county', pop: 200000 },
    { name: '灌南县', type: 'county', pop: 200000 },
    { name: '涟水县', type: 'county', pop: 200000 },
  ],
  '浙': [
    { name: '杭州市', type: 'capital', pop: 10000000 },
    { name: '宁波市', type: 'city', pop: 3000000 },
    { name: '温州市', type: 'city', pop: 3000000 },
    { name: '嘉兴市', type: 'city', pop: 3000000 },
    { name: '湖州市', type: 'city', pop: 3000000 },
    { name: '桐庐县', type: 'county', pop: 200000 },
    { name: '淳安县', type: 'county', pop: 200000 },
    { name: '建德市', type: 'county', pop: 200000 },
    { name: '象山县', type: 'county', pop: 200000 },
    { name: '宁海县', type: 'county', pop: 200000 },
    { name: '余姚市', type: 'county', pop: 200000 },
    { name: '慈溪市', type: 'county', pop: 200000 },
    { name: '永嘉县', type: 'county', pop: 200000 },
    { name: '平阳县', type: 'county', pop: 200000 },
    { name: '苍南县', type: 'county', pop: 200000 },
    { name: '文成县', type: 'county', pop: 200000 },
    { name: '泰顺县', type: 'county', pop: 200000 },
    { name: '瑞安市', type: 'county', pop: 200000 },
    { name: '乐清市', type: 'county', pop: 200000 },
    { name: '龙港市', type: 'county', pop: 200000 },
    { name: '嘉善县', type: 'county', pop: 200000 },
    { name: '海盐县', type: 'county', pop: 200000 },
    { name: '海宁市', type: 'county', pop: 200000 },
    { name: '平湖市', type: 'county', pop: 200000 },
    { name: '桐乡市', type: 'county', pop: 200000 },
  ],
  '皖': [
    { name: '合肥市', type: 'capital', pop: 10000000 },
    { name: '芜湖市', type: 'city', pop: 3000000 },
    { name: '蚌埠市', type: 'city', pop: 3000000 },
    { name: '淮南市', type: 'city', pop: 3000000 },
    { name: '马鞍山市', type: 'city', pop: 3000000 },
    { name: '长丰县', type: 'county', pop: 200000 },
    { name: '肥东县', type: 'county', pop: 200000 },
    { name: '肥西县', type: 'county', pop: 200000 },
    { name: '庐江县', type: 'county', pop: 200000 },
    { name: '巢湖市', type: 'county', pop: 200000 },
    { name: '南陵县', type: 'county', pop: 200000 },
    { name: '无为市', type: 'county', pop: 200000 },
    { name: '怀远县', type: 'county', pop: 200000 },
    { name: '五河县', type: 'county', pop: 200000 },
    { name: '固镇县', type: 'county', pop: 200000 },
    { name: '凤台县', type: 'county', pop: 200000 },
    { name: '寿县', type: 'county', pop: 200000 },
    { name: '当涂县', type: 'county', pop: 200000 },
    { name: '含山县', type: 'county', pop: 200000 },
    { name: '和县', type: 'county', pop: 200000 },
    { name: '濉溪县', type: 'county', pop: 200000 },
    { name: '枞阳县', type: 'county', pop: 200000 },
    { name: '怀宁县', type: 'county', pop: 200000 },
    { name: '太湖县', type: 'county', pop: 200000 },
    { name: '宿松县', type: 'county', pop: 200000 },
  ],
  '闽': [
    { name: '福州市', type: 'capital', pop: 10000000 },
    { name: '厦门市', type: 'city', pop: 3000000 },
    { name: '莆田市', type: 'city', pop: 3000000 },
    { name: '三明市', type: 'city', pop: 3000000 },
    { name: '泉州市', type: 'city', pop: 3000000 },
    { name: '闽侯县', type: 'county', pop: 200000 },
    { name: '连江县', type: 'county', pop: 200000 },
    { name: '罗源县', type: 'county', pop: 200000 },
    { name: '闽清县', type: 'county', pop: 200000 },
    { name: '永泰县', type: 'county', pop: 200000 },
    { name: '平潭县', type: 'county', pop: 200000 },
    { name: '福清市', type: 'county', pop: 200000 },
    { name: '仙游县', type: 'county', pop: 200000 },
    { name: '明溪县', type: 'county', pop: 200000 },
    { name: '清流县', type: 'county', pop: 200000 },
    { name: '宁化县', type: 'county', pop: 200000 },
    { name: '大田县', type: 'county', pop: 200000 },
    { name: '尤溪县', type: 'county', pop: 200000 },
    { name: '将乐县', type: 'county', pop: 200000 },
    { name: '泰宁县', type: 'county', pop: 200000 },
    { name: '建宁县', type: 'county', pop: 200000 },
    { name: '永安市', type: 'county', pop: 200000 },
    { name: '惠安县', type: 'county', pop: 200000 },
    { name: '安溪县', type: 'county', pop: 200000 },
    { name: '永春县', type: 'county', pop: 200000 },
  ],
  '赣': [
    { name: '南昌市', type: 'capital', pop: 10000000 },
    { name: '景德镇市', type: 'city', pop: 3000000 },
    { name: '萍乡市', type: 'city', pop: 3000000 },
    { name: '九江市', type: 'city', pop: 3000000 },
    { name: '新余市', type: 'city', pop: 3000000 },
    { name: '南昌县', type: 'county', pop: 200000 },
    { name: '安义县', type: 'county', pop: 200000 },
    { name: '进贤县', type: 'county', pop: 200000 },
    { name: '浮梁县', type: 'county', pop: 200000 },
    { name: '乐平市', type: 'county', pop: 200000 },
    { name: '莲花县', type: 'county', pop: 200000 },
    { name: '上栗县', type: 'county', pop: 200000 },
    { name: '芦溪县', type: 'county', pop: 200000 },
    { name: '武宁县', type: 'county', pop: 200000 },
    { name: '修水县', type: 'county', pop: 200000 },
    { name: '永修县', type: 'county', pop: 200000 },
    { name: '德安县', type: 'county', pop: 200000 },
    { name: '都昌县', type: 'county', pop: 200000 },
    { name: '湖口县', type: 'county', pop: 200000 },
    { name: '彭泽县', type: 'county', pop: 200000 },
    { name: '瑞昌市', type: 'county', pop: 200000 },
    { name: '共青城市', type: 'county', pop: 200000 },
    { name: '庐山市', type: 'county', pop: 200000 },
    { name: '分宜县', type: 'county', pop: 200000 },
    { name: '贵溪市', type: 'county', pop: 200000 },
  ],
  '鲁': [
    { name: '济南市', type: 'capital', pop: 10000000 },
    { name: '青岛市', type: 'mega', pop: 8000000 },
    { name: '淄博市', type: 'city', pop: 3000000 },
    { name: '枣庄市', type: 'city', pop: 3000000 },
    { name: '东营市', type: 'city', pop: 3000000 },
    { name: '平阴县', type: 'county', pop: 200000 },
    { name: '商河县', type: 'county', pop: 200000 },
    { name: '胶州市', type: 'county', pop: 200000 },
    { name: '平度市', type: 'county', pop: 200000 },
    { name: '莱西市', type: 'county', pop: 200000 },
    { name: '桓台县', type: 'county', pop: 200000 },
    { name: '高青县', type: 'county', pop: 200000 },
    { name: '沂源县', type: 'county', pop: 200000 },
    { name: '滕州市', type: 'county', pop: 200000 },
    { name: '利津县', type: 'county', pop: 200000 },
    { name: '广饶县', type: 'county', pop: 200000 },
    { name: '龙口市', type: 'county', pop: 200000 },
    { name: '莱阳市', type: 'county', pop: 200000 },
    { name: '莱州市', type: 'county', pop: 200000 },
    { name: '招远市', type: 'county', pop: 200000 },
    { name: '栖霞市', type: 'county', pop: 200000 },
    { name: '海阳市', type: 'county', pop: 200000 },
    { name: '临朐县', type: 'county', pop: 200000 },
    { name: '昌乐县', type: 'county', pop: 200000 },
    { name: '青州市', type: 'county', pop: 200000 },
  ],
  '豫': [
    { name: '郑州市', type: 'capital', pop: 10000000 },
    { name: '开封市', type: 'city', pop: 3000000 },
    { name: '洛阳市', type: 'city', pop: 3000000 },
    { name: '平顶山市', type: 'city', pop: 3000000 },
    { name: '安阳市', type: 'city', pop: 3000000 },
    { name: '中牟县', type: 'county', pop: 200000 },
    { name: '巩义市', type: 'county', pop: 200000 },
    { name: '荥阳市', type: 'county', pop: 200000 },
    { name: '新密市', type: 'county', pop: 200000 },
    { name: '新郑市', type: 'county', pop: 200000 },
    { name: '登封市', type: 'county', pop: 200000 },
    { name: '杞县', type: 'county', pop: 200000 },
    { name: '通许县', type: 'county', pop: 200000 },
    { name: '尉氏县', type: 'county', pop: 200000 },
    { name: '兰考县', type: 'county', pop: 200000 },
    { name: '新安县', type: 'county', pop: 200000 },
    { name: '栾川县', type: 'county', pop: 200000 },
    { name: '嵩县', type: 'county', pop: 200000 },
    { name: '汝阳县', type: 'county', pop: 200000 },
    { name: '宜阳县', type: 'county', pop: 200000 },
    { name: '洛宁县', type: 'county', pop: 200000 },
    { name: '伊川县', type: 'county', pop: 200000 },
    { name: '宝丰县', type: 'county', pop: 200000 },
    { name: '叶县', type: 'county', pop: 200000 },
    { name: '鲁山县', type: 'county', pop: 200000 },
  ],
  '鄂': [
    { name: '武汉市', type: 'capital', pop: 10000000 },
    { name: '黄石市', type: 'city', pop: 3000000 },
    { name: '十堰市', type: 'city', pop: 3000000 },
    { name: '宜昌市', type: 'city', pop: 3000000 },
    { name: '襄阳市', type: 'city', pop: 3000000 },
    { name: '阳新县', type: 'county', pop: 200000 },
    { name: '大冶市', type: 'county', pop: 200000 },
    { name: '郧西县', type: 'county', pop: 200000 },
    { name: '竹山县', type: 'county', pop: 200000 },
    { name: '竹溪县', type: 'county', pop: 200000 },
    { name: '房县', type: 'county', pop: 200000 },
    { name: '丹江口市', type: 'county', pop: 200000 },
    { name: '远安县', type: 'county', pop: 200000 },
    { name: '兴山县', type: 'county', pop: 200000 },
    { name: '秭归县', type: 'county', pop: 200000 },
    { name: '长阳土家族自治县', type: 'county', pop: 200000 },
    { name: '五峰土家族自治县', type: 'county', pop: 200000 },
    { name: '宜都市', type: 'county', pop: 200000 },
    { name: '当阳市', type: 'county', pop: 200000 },
    { name: '枝江市', type: 'county', pop: 200000 },
    { name: '南漳县', type: 'county', pop: 200000 },
    { name: '谷城县', type: 'county', pop: 200000 },
    { name: '保康县', type: 'county', pop: 200000 },
    { name: '老河口市', type: 'county', pop: 200000 },
    { name: '枣阳市', type: 'county', pop: 200000 },
  ],
  '湘': [
    { name: '长沙市', type: 'capital', pop: 10000000 },
    { name: '株洲市', type: 'city', pop: 3000000 },
    { name: '湘潭市', type: 'city', pop: 3000000 },
    { name: '衡阳市', type: 'city', pop: 3000000 },
    { name: '邵阳市', type: 'city', pop: 3000000 },
    { name: '长沙县', type: 'county', pop: 200000 },
    { name: '浏阳市', type: 'county', pop: 200000 },
    { name: '宁乡市', type: 'county', pop: 200000 },
    { name: '攸县', type: 'county', pop: 200000 },
    { name: '茶陵县', type: 'county', pop: 200000 },
    { name: '炎陵县', type: 'county', pop: 200000 },
    { name: '醴陵市', type: 'county', pop: 200000 },
    { name: '湘潭县', type: 'county', pop: 200000 },
    { name: '湘乡市', type: 'county', pop: 200000 },
    { name: '韶山市', type: 'county', pop: 200000 },
    { name: '衡阳县', type: 'county', pop: 200000 },
    { name: '衡南县', type: 'county', pop: 200000 },
    { name: '衡山县', type: 'county', pop: 200000 },
    { name: '衡东县', type: 'county', pop: 200000 },
    { name: '祁东县', type: 'county', pop: 200000 },
    { name: '耒阳市', type: 'county', pop: 200000 },
    { name: '常宁市', type: 'county', pop: 200000 },
    { name: '新邵县', type: 'county', pop: 200000 },
    { name: '邵阳县', type: 'county', pop: 200000 },
    { name: '隆回县', type: 'county', pop: 200000 },
  ],
  '粤': [
    { name: '广州市', type: 'capital', pop: 10000000 },
    { name: '韶关市', type: 'city', pop: 3000000 },
    { name: '深圳市', type: 'mega', pop: 8000000 },
    { name: '珠海市', type: 'city', pop: 3000000 },
    { name: '汕头市', type: 'city', pop: 3000000 },
    { name: '始兴县', type: 'county', pop: 200000 },
    { name: '仁化县', type: 'county', pop: 200000 },
    { name: '翁源县', type: 'county', pop: 200000 },
    { name: '乳源瑶族自治县', type: 'county', pop: 200000 },
    { name: '新丰县', type: 'county', pop: 200000 },
    { name: '乐昌市', type: 'county', pop: 200000 },
    { name: '南雄市', type: 'county', pop: 200000 },
    { name: '南澳县', type: 'county', pop: 200000 },
    { name: '台山市', type: 'county', pop: 200000 },
    { name: '开平市', type: 'county', pop: 200000 },
    { name: '鹤山市', type: 'county', pop: 200000 },
    { name: '恩平市', type: 'county', pop: 200000 },
    { name: '遂溪县', type: 'county', pop: 200000 },
    { name: '徐闻县', type: 'county', pop: 200000 },
    { name: '廉江市', type: 'county', pop: 200000 },
    { name: '雷州市', type: 'county', pop: 200000 },
    { name: '吴川市', type: 'county', pop: 200000 },
    { name: '高州市', type: 'county', pop: 200000 },
    { name: '化州市', type: 'county', pop: 200000 },
    { name: '信宜市', type: 'county', pop: 200000 },
  ],
  '桂': [
    { name: '南宁市', type: 'capital', pop: 10000000 },
    { name: '柳州市', type: 'city', pop: 3000000 },
    { name: '桂林市', type: 'city', pop: 3000000 },
    { name: '梧州市', type: 'city', pop: 3000000 },
    { name: '北海市', type: 'city', pop: 3000000 },
    { name: '隆安县', type: 'county', pop: 200000 },
    { name: '马山县', type: 'county', pop: 200000 },
    { name: '上林县', type: 'county', pop: 200000 },
    { name: '宾阳县', type: 'county', pop: 200000 },
    { name: '横州市', type: 'county', pop: 200000 },
    { name: '柳城县', type: 'county', pop: 200000 },
    { name: '鹿寨县', type: 'county', pop: 200000 },
    { name: '融安县', type: 'county', pop: 200000 },
    { name: '融水苗族自治县', type: 'county', pop: 200000 },
    { name: '三江侗族自治县', type: 'county', pop: 200000 },
    { name: '阳朔县', type: 'county', pop: 200000 },
    { name: '灵川县', type: 'county', pop: 200000 },
    { name: '全州县', type: 'county', pop: 200000 },
    { name: '兴安县', type: 'county', pop: 200000 },
    { name: '永福县', type: 'county', pop: 200000 },
    { name: '灌阳县', type: 'county', pop: 200000 },
    { name: '龙胜各族自治县', type: 'county', pop: 200000 },
    { name: '资源县', type: 'county', pop: 200000 },
    { name: '平乐县', type: 'county', pop: 200000 },
    { name: '恭城瑶族自治县', type: 'county', pop: 200000 },
  ],
  '琼': [
    { name: '海口市', type: 'capital', pop: 10000000 },
    { name: '三亚市', type: 'city', pop: 3000000 },
    { name: '三沙市', type: 'city', pop: 3000000 },
    { name: '儋州市', type: 'city', pop: 3000000 },
    { name: '省直辖县级行政区划', type: 'city', pop: 3000000 },
    { name: '西沙群岛', type: 'county', pop: 200000 },
    { name: '南沙群岛', type: 'county', pop: 200000 },
    { name: '中沙群岛的岛礁及其海域', type: 'county', pop: 200000 },
    { name: '五指山市', type: 'county', pop: 200000 },
    { name: '琼海市', type: 'county', pop: 200000 },
    { name: '文昌市', type: 'county', pop: 200000 },
    { name: '万宁市', type: 'county', pop: 200000 },
    { name: '东方市', type: 'county', pop: 200000 },
    { name: '定安县', type: 'county', pop: 200000 },
    { name: '屯昌县', type: 'county', pop: 200000 },
    { name: '澄迈县', type: 'county', pop: 200000 },
    { name: '临高县', type: 'county', pop: 200000 },
    { name: '白沙黎族自治县', type: 'county', pop: 200000 },
    { name: '昌江黎族自治县', type: 'county', pop: 200000 },
    { name: '乐东黎族自治县', type: 'county', pop: 200000 },
    { name: '陵水黎族自治县', type: 'county', pop: 200000 },
    { name: '保亭黎族苗族自治县', type: 'county', pop: 200000 },
    { name: '琼中黎族苗族自治县', type: 'county', pop: 200000 },
  ],
  '渝': [
    { name: '市辖区', type: 'capital', pop: 10000000 },
    { name: '万州区', type: 'county', pop: 200000 },
    { name: '涪陵区', type: 'county', pop: 200000 },
    { name: '黔江区', type: 'county', pop: 200000 },
    { name: '开州区', type: 'county', pop: 200000 },
    { name: '武隆区', type: 'county', pop: 200000 },
    { name: '城口县', type: 'county', pop: 200000 },
    { name: '忠县', type: 'county', pop: 200000 },
    { name: '云阳县', type: 'county', pop: 200000 },
    { name: '奉节县', type: 'county', pop: 200000 },
    { name: '巫山县', type: 'county', pop: 200000 },
    { name: '巫溪县', type: 'county', pop: 200000 },
  ],
  '川': [
    { name: '成都市', type: 'capital', pop: 10000000 },
    { name: '自贡市', type: 'city', pop: 3000000 },
    { name: '攀枝花市', type: 'city', pop: 3000000 },
    { name: '泸州市', type: 'city', pop: 3000000 },
    { name: '德阳市', type: 'city', pop: 3000000 },
    { name: '金堂县', type: 'county', pop: 200000 },
    { name: '大邑县', type: 'county', pop: 200000 },
    { name: '蒲江县', type: 'county', pop: 200000 },
    { name: '都江堰市', type: 'county', pop: 200000 },
    { name: '彭州市', type: 'county', pop: 200000 },
    { name: '邛崃市', type: 'county', pop: 200000 },
    { name: '崇州市', type: 'county', pop: 200000 },
    { name: '简阳市', type: 'county', pop: 200000 },
    { name: '荣县', type: 'county', pop: 200000 },
    { name: '富顺县', type: 'county', pop: 200000 },
    { name: '米易县', type: 'county', pop: 200000 },
    { name: '盐边县', type: 'county', pop: 200000 },
    { name: '泸县', type: 'county', pop: 200000 },
    { name: '合江县', type: 'county', pop: 200000 },
    { name: '叙永县', type: 'county', pop: 200000 },
    { name: '古蔺县', type: 'county', pop: 200000 },
    { name: '中江县', type: 'county', pop: 200000 },
    { name: '广汉市', type: 'county', pop: 200000 },
    { name: '什邡市', type: 'county', pop: 200000 },
    { name: '绵竹市', type: 'county', pop: 200000 },
  ],
  '黔': [
    { name: '贵阳市', type: 'capital', pop: 10000000 },
    { name: '六盘水市', type: 'city', pop: 3000000 },
    { name: '遵义市', type: 'city', pop: 3000000 },
    { name: '安顺市', type: 'city', pop: 3000000 },
    { name: '毕节市', type: 'city', pop: 3000000 },
    { name: '开阳县', type: 'county', pop: 200000 },
    { name: '息烽县', type: 'county', pop: 200000 },
    { name: '修文县', type: 'county', pop: 200000 },
    { name: '清镇市', type: 'county', pop: 200000 },
    { name: '盘州市', type: 'county', pop: 200000 },
    { name: '桐梓县', type: 'county', pop: 200000 },
    { name: '绥阳县', type: 'county', pop: 200000 },
    { name: '正安县', type: 'county', pop: 200000 },
    { name: '道真仡佬族苗族自治县', type: 'county', pop: 200000 },
    { name: '务川仡佬族苗族自治县', type: 'county', pop: 200000 },
    { name: '凤冈县', type: 'county', pop: 200000 },
    { name: '湄潭县', type: 'county', pop: 200000 },
    { name: '余庆县', type: 'county', pop: 200000 },
    { name: '习水县', type: 'county', pop: 200000 },
    { name: '赤水市', type: 'county', pop: 200000 },
    { name: '仁怀市', type: 'county', pop: 200000 },
    { name: '普定县', type: 'county', pop: 200000 },
    { name: '镇宁布依族苗族自治县', type: 'county', pop: 200000 },
    { name: '关岭布依族苗族自治县', type: 'county', pop: 200000 },
    { name: '紫云苗族布依族自治县', type: 'county', pop: 200000 },
  ],
  '滇': [
    { name: '昆明市', type: 'capital', pop: 10000000 },
    { name: '曲靖市', type: 'city', pop: 3000000 },
    { name: '玉溪市', type: 'city', pop: 3000000 },
    { name: '保山市', type: 'city', pop: 3000000 },
    { name: '昭通市', type: 'city', pop: 3000000 },
    { name: '富民县', type: 'county', pop: 200000 },
    { name: '宜良县', type: 'county', pop: 200000 },
    { name: '石林彝族自治县', type: 'county', pop: 200000 },
    { name: '嵩明县', type: 'county', pop: 200000 },
    { name: '禄劝彝族苗族自治县', type: 'county', pop: 200000 },
    { name: '寻甸回族彝族自治县', type: 'county', pop: 200000 },
    { name: '安宁市', type: 'county', pop: 200000 },
    { name: '陆良县', type: 'county', pop: 200000 },
    { name: '师宗县', type: 'county', pop: 200000 },
    { name: '罗平县', type: 'county', pop: 200000 },
    { name: '富源县', type: 'county', pop: 200000 },
    { name: '会泽县', type: 'county', pop: 200000 },
    { name: '宣威市', type: 'county', pop: 200000 },
    { name: '通海县', type: 'county', pop: 200000 },
    { name: '华宁县', type: 'county', pop: 200000 },
    { name: '易门县', type: 'county', pop: 200000 },
    { name: '峨山彝族自治县', type: 'county', pop: 200000 },
    { name: '新平彝族傣族自治县', type: 'county', pop: 200000 },
    { name: '元江哈尼族彝族傣族自治县', type: 'county', pop: 200000 },
    { name: '澄江市', type: 'county', pop: 200000 },
  ],
  '藏': [
    { name: '拉萨市', type: 'capital', pop: 10000000 },
    { name: '日喀则市', type: 'city', pop: 3000000 },
    { name: '昌都市', type: 'city', pop: 3000000 },
    { name: '林芝市', type: 'city', pop: 3000000 },
    { name: '山南市', type: 'city', pop: 3000000 },
    { name: '林周县', type: 'county', pop: 200000 },
    { name: '当雄县', type: 'county', pop: 200000 },
    { name: '尼木县', type: 'county', pop: 200000 },
    { name: '曲水县', type: 'county', pop: 200000 },
    { name: '墨竹工卡县', type: 'county', pop: 200000 },
    { name: '南木林县', type: 'county', pop: 200000 },
    { name: '江孜县', type: 'county', pop: 200000 },
    { name: '定日县', type: 'county', pop: 200000 },
    { name: '萨迦县', type: 'county', pop: 200000 },
    { name: '拉孜县', type: 'county', pop: 200000 },
    { name: '昂仁县', type: 'county', pop: 200000 },
    { name: '谢通门县', type: 'county', pop: 200000 },
    { name: '白朗县', type: 'county', pop: 200000 },
    { name: '仁布县', type: 'county', pop: 200000 },
    { name: '康马县', type: 'county', pop: 200000 },
    { name: '定结县', type: 'county', pop: 200000 },
    { name: '仲巴县', type: 'county', pop: 200000 },
    { name: '亚东县', type: 'county', pop: 200000 },
    { name: '吉隆县', type: 'county', pop: 200000 },
    { name: '聂拉木县', type: 'county', pop: 200000 },
  ],
  '陕': [
    { name: '西安市', type: 'capital', pop: 10000000 },
    { name: '铜川市', type: 'city', pop: 3000000 },
    { name: '宝鸡市', type: 'city', pop: 3000000 },
    { name: '咸阳市', type: 'city', pop: 3000000 },
    { name: '渭南市', type: 'city', pop: 3000000 },
    { name: '蓝田县', type: 'county', pop: 200000 },
    { name: '周至县', type: 'county', pop: 200000 },
    { name: '宜君县', type: 'county', pop: 200000 },
    { name: '岐山县', type: 'county', pop: 200000 },
    { name: '扶风县', type: 'county', pop: 200000 },
    { name: '眉县', type: 'county', pop: 200000 },
    { name: '陇县', type: 'county', pop: 200000 },
    { name: '千阳县', type: 'county', pop: 200000 },
    { name: '麟游县', type: 'county', pop: 200000 },
    { name: '凤县', type: 'county', pop: 200000 },
    { name: '太白县', type: 'county', pop: 200000 },
    { name: '三原县', type: 'county', pop: 200000 },
    { name: '泾阳县', type: 'county', pop: 200000 },
    { name: '乾县', type: 'county', pop: 200000 },
    { name: '礼泉县', type: 'county', pop: 200000 },
    { name: '永寿县', type: 'county', pop: 200000 },
    { name: '长武县', type: 'county', pop: 200000 },
    { name: '旬邑县', type: 'county', pop: 200000 },
    { name: '淳化县', type: 'county', pop: 200000 },
    { name: '武功县', type: 'county', pop: 200000 },
  ],
  '甘': [
    { name: '兰州市', type: 'capital', pop: 10000000 },
    { name: '嘉峪关市', type: 'city', pop: 3000000 },
    { name: '金昌市', type: 'city', pop: 3000000 },
    { name: '白银市', type: 'city', pop: 3000000 },
    { name: '天水市', type: 'city', pop: 3000000 },
    { name: '永登县', type: 'county', pop: 200000 },
    { name: '皋兰县', type: 'county', pop: 200000 },
    { name: '榆中县', type: 'county', pop: 200000 },
    { name: '永昌县', type: 'county', pop: 200000 },
    { name: '靖远县', type: 'county', pop: 200000 },
    { name: '会宁县', type: 'county', pop: 200000 },
    { name: '景泰县', type: 'county', pop: 200000 },
    { name: '清水县', type: 'county', pop: 200000 },
    { name: '秦安县', type: 'county', pop: 200000 },
    { name: '甘谷县', type: 'county', pop: 200000 },
    { name: '武山县', type: 'county', pop: 200000 },
    { name: '张家川回族自治县', type: 'county', pop: 200000 },
    { name: '民勤县', type: 'county', pop: 200000 },
    { name: '古浪县', type: 'county', pop: 200000 },
    { name: '天祝藏族自治县', type: 'county', pop: 200000 },
    { name: '肃南裕固族自治县', type: 'county', pop: 200000 },
    { name: '民乐县', type: 'county', pop: 200000 },
    { name: '临泽县', type: 'county', pop: 200000 },
    { name: '高台县', type: 'county', pop: 200000 },
    { name: '山丹县', type: 'county', pop: 200000 },
  ],
  '青': [
    { name: '西宁市', type: 'capital', pop: 10000000 },
    { name: '海东市', type: 'city', pop: 3000000 },
    { name: '海北藏族自治州', type: 'city', pop: 3000000 },
    { name: '黄南藏族自治州', type: 'city', pop: 3000000 },
    { name: '海南藏族自治州', type: 'city', pop: 3000000 },
    { name: '大通回族土族自治县', type: 'county', pop: 200000 },
    { name: '湟源县', type: 'county', pop: 200000 },
    { name: '民和回族土族自治县', type: 'county', pop: 200000 },
    { name: '互助土族自治县', type: 'county', pop: 200000 },
    { name: '化隆回族自治县', type: 'county', pop: 200000 },
    { name: '循化撒拉族自治县', type: 'county', pop: 200000 },
    { name: '门源回族自治县', type: 'county', pop: 200000 },
    { name: '祁连县', type: 'county', pop: 200000 },
    { name: '海晏县', type: 'county', pop: 200000 },
    { name: '刚察县', type: 'county', pop: 200000 },
    { name: '同仁市', type: 'county', pop: 200000 },
    { name: '尖扎县', type: 'county', pop: 200000 },
    { name: '泽库县', type: 'county', pop: 200000 },
    { name: '河南蒙古族自治县', type: 'county', pop: 200000 },
    { name: '共和县', type: 'county', pop: 200000 },
    { name: '同德县', type: 'county', pop: 200000 },
    { name: '贵德县', type: 'county', pop: 200000 },
    { name: '兴海县', type: 'county', pop: 200000 },
    { name: '贵南县', type: 'county', pop: 200000 },
    { name: '玛沁县', type: 'county', pop: 200000 },
  ],
  '宁': [
    { name: '银川市', type: 'capital', pop: 10000000 },
    { name: '石嘴山市', type: 'city', pop: 3000000 },
    { name: '吴忠市', type: 'city', pop: 3000000 },
    { name: '固原市', type: 'city', pop: 3000000 },
    { name: '中卫市', type: 'city', pop: 3000000 },
    { name: '永宁县', type: 'county', pop: 200000 },
    { name: '贺兰县', type: 'county', pop: 200000 },
    { name: '灵武市', type: 'county', pop: 200000 },
    { name: '平罗县', type: 'county', pop: 200000 },
    { name: '盐池县', type: 'county', pop: 200000 },
    { name: '同心县', type: 'county', pop: 200000 },
    { name: '青铜峡市', type: 'county', pop: 200000 },
    { name: '西吉县', type: 'county', pop: 200000 },
    { name: '隆德县', type: 'county', pop: 200000 },
    { name: '泾源县', type: 'county', pop: 200000 },
    { name: '彭阳县', type: 'county', pop: 200000 },
    { name: '中宁县', type: 'county', pop: 200000 },
    { name: '海原县', type: 'county', pop: 200000 },
  ],
  '新': [
    { name: '乌鲁木齐市', type: 'capital', pop: 10000000 },
    { name: '克拉玛依市', type: 'city', pop: 3000000 },
    { name: '吐鲁番市', type: 'city', pop: 3000000 },
    { name: '哈密市', type: 'city', pop: 3000000 },
    { name: '昌吉回族自治州', type: 'city', pop: 3000000 },
    { name: '乌鲁木齐县', type: 'county', pop: 200000 },
    { name: '鄯善县', type: 'county', pop: 200000 },
    { name: '托克逊县', type: 'county', pop: 200000 },
    { name: '巴里坤哈萨克自治县', type: 'county', pop: 200000 },
    { name: '伊吾县', type: 'county', pop: 200000 },
    { name: '昌吉市', type: 'county', pop: 200000 },
    { name: '阜康市', type: 'county', pop: 200000 },
    { name: '呼图壁县', type: 'county', pop: 200000 },
    { name: '玛纳斯县', type: 'county', pop: 200000 },
    { name: '奇台县', type: 'county', pop: 200000 },
    { name: '吉木萨尔县', type: 'county', pop: 200000 },
    { name: '木垒哈萨克自治县', type: 'county', pop: 200000 },
    { name: '博乐市', type: 'county', pop: 200000 },
    { name: '阿拉山口市', type: 'county', pop: 200000 },
    { name: '精河县', type: 'county', pop: 200000 },
    { name: '温泉县', type: 'county', pop: 200000 },
    { name: '库尔勒市', type: 'county', pop: 200000 },
    { name: '轮台县', type: 'county', pop: 200000 },
    { name: '尉犁县', type: 'county', pop: 200000 },
    { name: '若羌县', type: 'county', pop: 200000 },
  ],
};



// ─────────────────────────────────────────────
// 4. 街道/乡镇数据（2024年统计用区划代码，来源：国家统计局）
//    替换旧通用模板为 31 省真实乡镇/街道数据
//    数据源：国家统计局2023年6月30日统计用区划代码（2024版）
// ─────────────────────────────────────────────
const STREET_TEMPLATES = {
  // 通用备选池（capitals 和 cities 类型使用）
  capital: [
    '中山路街道','解放路街道','建国路街道','文化路街道',
    '新城街道','东风路街道','人民路街道','光明路街道',
    '和平街道','幸福路街道','工农路街道','兴隆街道',
  ],
  city: [
    '城关镇','红旗街道','东城街道','西城街道',
    '南关街道','北关街道','民主路街道','胜利街道',
    '建设路街道','长安街道','安定街道','向阳街道',
  ],
};

// ─────────────────────────────────────────────
// 各省真实街道/乡镇池（来自Excel数据）
// ─────────────────────────────────────────────
const COUNTY_STREETS = {
  '京': ['东华门街道', '景山街道', '交道口街道', '安定门街道', '北新桥街道', '东四街道', '朝阳门街道', '建国门街道', '东直门街道', '和平里街道', '前门街道', '崇文门外街道', '东花市街道', '龙潭街道', '体育馆路街道', '天坛街道', '永定门外街道', '西长安街街道', '新街口街道', '月坛街道', '展览路街道', '德胜街道', '金融街街道', '什刹海街道', '大栅栏街道', '天桥街道', '椿树街道', '陶然亭街道', '广安门内街道', '牛街街道', '白纸坊街道', '广安门外街道', '建外街道', '朝外街道', '呼家楼街道', '三里屯街道', '左家庄街道', '香河园街道', '和平街街道', '安贞街道', '亚运村街道', '小关街道', '酒仙桥街道', '麦子店街道', '团结湖街道', '六里屯街道', '八里庄街道', '双井街道', '劲松街道', '潘家园街道'],
  '津': ['劝业场街道', '小白楼街道', '五大道街道', '新兴街道', '南营门街道', '南市街道', '大王庄街道', '大直沽街道', '中山门街道', '富民路街道', '二号桥街道', '春华街道', '唐家口街道', '向阳楼街道', '常州道街道', '上杭路街道', '东新街道', '鲁山道街道', '天津铁厂街道', '大营门街道', '下瓦房街道', '桃园街道', '挂甲寺街道', '马场街道', '越秀路街道', '友谊路街道', '天塔街道', '尖山街道', '陈塘庄街道', '柳林街道', '东海街道', '梅江街道', '太湖路街道', '长虹街道', '鼓楼街道', '兴南街道', '广开街道', '万兴街道', '学府街道', '向阳路街道', '嘉陵道街道', '王顶堤街道', '水上公园街道', '体育中心街道', '华苑街道', '光复道街道', '望海楼街道', '鸿顺里街道', '新开河街道', '铁东路街道'],
  '冀': ['建北街道', '青园街道', '广安街道', '育才街道', '跃进街道', '河东街道', '长丰街道', '谈固街道', '中山东路街道', '阜康街道', '建安街道', '胜北街道', '西兆通镇', '南村镇', '高营镇', '桃园镇', '东里街道', '中山街道', '南长街道', '维明街道', '友谊街道', '红旗街道', '新石街道', '苑东街道', '西里街道', '振头街道', '留营街道', '长兴街道', '彭后街道', '东风街道', '东华街道', '休门街道', '汇通街道', '革新街街道', '新华路街道', '宁安街道', '东焦街道', '西苑街道', '合作路街道', '联盟街道', '石岗街道', '天苑街道', '北苑街道', '赵陵铺路街道', '西三庄街道', '大郭街道', '杜北街道', '赵佗路街道', '矿市街道', '四微街道'],
  '晋': ['坞城街道', '营盘街道', '北营街道', '平阳路街道', '黄陵街道', '小店街道', '龙城街道', '北格镇', '西温庄乡', '刘家堡乡', '柳巷街道', '文庙街道', '庙前街道', '迎泽街道', '桥东街道', '老军营街道', '郝庄镇', '巨轮街道', '三桥街道', '鼓楼街道', '杏花岭街道', '坝陵桥街道', '大东关街道', '职工新街街道', '敦化坊街道', '涧河街道', '杨家峪街道', '享堂街道', '中涧河镇', '尖草坪街道', '光社街道', '上兰街道', '南寨街道', '迎新街街道', '古城街道', '汇丰街道', '柴村街道', '新城街道', '向阳镇', '阳曲镇', '柏板乡', '西墕乡', '太原中北高新技术产业开发区', '千峰街道', '下元街道', '和平街道', '兴华街道', '万柏林街道', '杜儿坪街道', '白家庄街道'],
  '蒙': ['海拉尔东路街道', '锡林北路街道', '中山东路街道', '东街街道', '西街街道', '东风路街道', '迎新路街道', '成吉思汗大街街道', '保合少镇', '新城区鸿盛高科技园区', '呼伦路街道', '丁香路街道', '东河街道', '新华西路街道', '中山西路街道', '光明路街道', '海拉尔西路街道', '环河街街道', '通道街街道', '钢铁路街道', '攸攸板镇', '阿拉善北路街道', '小召前街街道', '兴隆巷街道', '长和廊街道', '石东路街道', '大南街街道', '鄂尔多斯路街道', '西菜园街道', '昭君路街道', '小黑河镇', '裕隆工业园区', '人民路街道', '大学西路街道', '乌兰察布东路街道', '大学东路街道', '中专路街道', '昭乌达南路街道', '巴彦街道', '敕勒川路街道', '榆林镇', '黄合少镇', '金河镇', '察素齐镇', '毕克齐镇', '善岱镇', '台阁牧镇', '白庙子镇', '沙尔沁镇', '敕勒川镇'],
  '辽': ['浑河湾街道', '新华街道', '马路湾街道', '南湖街道', '长白街道', '太原街街道', '北市场街道', '南市场街道', '沈水湾街道', '浑河站西街道', '滨河街道', '万莲街道', '朱剪炉街道', '北站街道', '风雨坛街道', '皇城街道', '五里河街道', '南塔街道', '泉园街道', '马官桥街道', '东陵街道', '大北街道', '万泉街道', '文官街道', '二台子街道', '津桥街道', '东站街道', '长安街道', '东塔街道', '上园街道', '前进街道', '三台子街道', '黄河街道', '华山街道', '明廉街道', '新乐街道', '舍利塔街道', '北塔街道', '陵东街道', '鸭绿江街道', '四台子街道', '昆明湖街道', '工人村街道', '启工街道', '笃工街道', '兴华街道', '霁虹街道', '凌空街道', '重工街道', '兴顺街道'],
  '吉': ['南岭街道', '自强街道', '民康街道', '新春街道', '长通街道', '全安街道', '曙光街道', '永吉街道', '桃源街道', '鸿城街道', '明珠街道', '富裕街道', '盛世街道', '幸福乡', '站前街道', '群英街道', '兴业街道', '凯旋街道', '团山街道', '柳影街道', '欣园街道', '长德街道', '新广街道', '新隆街道', '长新街道', '兰家镇', '米沙子镇', '万宝镇', '合隆镇', '前进街道', '桂林街道', '南湖街道', '永昌街道', '重庆街道', '清和街道', '红旗街道', '湖西街道', '富锋街道', '乐山镇', '永春镇', '东盛街道', '吉林街道', '荣光街道', '东站街道', '远达街道', '八里堡街道', '长青街道', '东惠街道', '英俊镇', '劝农山镇'],
  '黑': ['兆麟街道', '新阳路街道', '抚顺街道', '共乐街道', '新华街道', '城乡路街道', '工农街道', '尚志街道', '斯大林街道', '通江街道', '经纬街道', '工程街道', '安静街道', '安和街道', '正阳河街道', '建国街道', '康安街道', '爱建街道', '群力街道', '太平镇', '新发镇', '新农镇', '榆树镇', '花园街道', '奋斗路街道', '革新街道', '文化街道', '大成街道', '芦家街道', '荣市街道', '燎原街道', '松花江街道', '曲线街道', '通达街道', '七政街道', '和兴路街道', '哈西街道', '保健路街道', '先锋路街道', '新春街道', '跃进街道', '王岗镇', '红旗满族乡', '红旗农场', '南岗区农垦', '靖宇街道', '太古街道', '东莱街道', '滨江街道', '仁里街道'],
  '沪': ['南京东路街道', '外滩街道', '半淞园路街道', '小东门街道', '豫园街道', '老西门街道', '五里桥街道', '打浦桥街道', '淮海中路街道', '瑞金二路街道', '天平路街道', '湖南路街道', '斜土路街道', '枫林路街道', '长桥街道', '田林街道', '虹梅路街道', '康健新村街道', '徐家汇街道', '凌云路街道', '龙华街道', '漕河泾街道', '华泾镇', '漕河泾新兴技术开发区', '华阳路街道', '江苏路街道', '新华路街道', '周家桥街道', '天山路街道', '仙霞新村街道', '虹桥街道', '程家桥街道', '北新泾街道', '新泾镇', '江宁路街道', '石门二路街道', '南京西路街道', '静安寺街道', '曹家渡街道', '天目西路街道', '北站街道', '宝山路街道', '共和新路街道', '大宁路街道', '彭浦新村街道', '临汾路街道', '芷江西路街道', '彭浦镇', '曹杨新村街道', '长风新村街道'],
  '苏': ['梅园新村街道', '新街口街道', '玄武门街道', '锁金村街道', '红山街道', '孝陵卫街道', '玄武湖街道', '徐庄高新技术产业开发区', '秦虹街道', '夫子庙街道', '红花街道', '双塘街道', '中华门街道', '五老村街道', '洪武路街道', '大光路街道', '瑞金路街道', '月牙湖街道', '光华路街道', '朝天宫街道', '夫子庙秦淮风光带', '高新园区', '新城发展服务', '新街口商务商贸街区', '莫愁湖街道', '沙洲街道', '双闸街道', '江心洲街道', '兴隆街道', '南苑街道', '宁海路街道', '华侨路街道', '湖南路街道', '中央门街道', '挹江门街道', '江东街道', '凤凰街道', '下关街道', '热河南路街道', '幕府山街道', '建宁路街道', '宝塔桥街道', '小市街道', '泰山街道', '顶山街道', '沿江街道', '江浦街道', '桥林街道', '汤泉街道', '盘城街道'],
  '浙': ['清波街道', '湖滨街道', '小营街道', '南星街道', '紫阳街道', '望江街道', '凯旋街道', '采荷街道', '闸弄口街道', '四季青街道', '彭埠街道', '笕桥街道', '丁兰街道', '九堡街道', '米市巷街道', '湖墅街道', '小河街道', '和睦街道', '拱宸桥街道', '大关街道', '上塘街道', '祥符街道', '康桥街道', '半山街道', '天水街道', '武林街道', '长庆街道', '潮鸣街道', '朝晖街道', '文晖街道', '东新街道', '石桥街道', '北山街道', '西溪街道', '翠苑街道', '古荡街道', '西湖街道', '留下街道', '转塘街道', '蒋村街道', '灵隐街道', '文新街道', '三墩镇', '双浦镇', '西兴街道', '长河街道', '浦沿街道', '城厢街道', '北干街道', '蜀山街道'],
  '皖': ['明光路街道', '胜利路街道', '三里街街道', '铜陵路街道', '七里站街道', '红光街道', '和平路街道', '城东街道', '长淮街道', '方庙街道', '嘉山路街道', '大兴镇', '合肥龙岗综合经济开发区', '亳州路街道', '双岗街道', '杏林街道', '海棠街道', '杏花村街道', '逍遥津街道', '三孝口街道', '四里河街道', '大杨镇', '三十岗乡', '庐阳工业区（林店街道）', '三里庵街道', '稻香村街道', '琥珀街道', '南七街道', '西园街道', '五里墩街道', '荷叶地街道', '笔架山街道', '井岗镇', '南岗镇', '小庙镇', '蜀山新产业园区', '骆岗街道', '常青街道', '芜湖路街道', '包公街道', '望湖街道', '义城街道', '烟墩街道', '万年埠街道', '同安街道', '淝河镇', '大圩镇', '滨湖世纪社区', '方兴社区', '水湖镇'],
  '闽': ['鼓东街道', '鼓西街道', '温泉街道', '东街街道', '南街街道', '安泰街道', '华大街道', '水部街道', '五凤街道', '洪山镇', '瀛洲街道', '后洲街道', '义洲街道', '新港街道', '上海街道', '苍霞街道', '茶亭街道', '洋中街道', '鳌峰街道', '宁化街道', '仓前街道', '东升街道', '对湖街道', '临江街道', '三叉街街道', '上渡街道', '下渡街道', '金山街道', '仓山镇', '城门镇', '盖山镇', '建新镇', '螺洲镇', '红星农场', '罗星街道', '马尾镇', '亭江镇', '琅岐镇', '茶园街道', '王庄街道', '象园街道', '鼓山镇', '新店镇', '岳峰镇', '宦溪镇', '寿山乡', '日溪乡', '吴航街道', '航城街道', '营前街道'],
  '赣': ['滕王阁街道', '百花洲街道', '墩子塘街道', '大院街道', '豫章街道', '董家窑街道', '彭家桥街道', '扬子洲镇', '贤士湖管理处', '扬农管理处', '南浦街道', '朝阳洲街道', '广润门街道', '绳金塔街道', '丁公路街道', '南站街道', '桃源街道', '朝农街道', '桃花街道', '九洲街道', '洪都街道', '京山街道', '三家店街道', '岱山街道', '徐家坊街道', '青云谱镇', '江西青云谱新经济产业集聚区', '青山路街道', '上海路街道', '南钢街道', '站东街道', '京东镇', '罗家镇', '湖坊镇', '塘山镇', '江西青山湖高新技术产业园区', '艾溪湖管理处', '站前街道', '幸福街道', '蛟桥街道', '长堎街道', '欣悦湖街道', '望城镇', '西山镇', '石岗镇', '松湖镇', '樵舍镇', '乐化镇', '溪霞镇', '象山镇'],
  '鲁': ['解放路街道', '千佛山街道', '趵突泉街道', '泉城路街道', '大明湖街道', '东关街道', '文东街道', '建新街道', '甸柳街道', '燕山街道', '姚家街道', '龙洞街道', '智远街道', '大观园街道', '杆石桥街道', '四里村街道', '魏家庄街道', '二七街道', '七里山街道', '六里山街道', '舜玉路街道', '泺源街道', '王官庄街道', '舜耕街道', '白马山街道', '七贤街道', '十六里河街道', '兴隆街道', '党家街道', '陡沟街道', '振兴街街道', '中大槐树街道', '道德街街道', '西市场街道', '五里沟街道', '营市街街道', '青年公园街道', '南辛庄街道', '段店北路街道', '张庄路街道', '匡山街道', '美里湖街道', '腊山街道', '兴福街道', '玉清湖街道', '吴家堡街道', '无影山街道', '天桥东街街道', '北村街道', '南村街道'],
  '豫': ['林山寨街道', '建设路街道', '棉纺路街道', '秦岭路街道', '桐柏路街道', '三官庙街道', '绿东村街道', '汝河路街道', '航海西路街道', '中原西路街道', '西流湖街道', '须水街道', '莲湖街道', '柳湖街道', '淮河路街道', '铭功路街道', '一马路街道', '蜜蜂张街道', '五里堡街道', '大学路街道', '建中街街道', '福华街街道', '德化街街道', '嵩山路街道', '京广路街道', '长江路街道', '人和路街道', '侯寨街道', '金水源街道', '马寨镇', '北下街街道', '西大街街道', '南关街街道', '城东路街道', '东大街街道', '二里岗街道', '陇海马路街道', '紫荆山南路街道', '航海东路街道', '十八里河街道', '南曹街道', '金岱街道', '圃田乡', '商都路街道', '经八路街道', '花园路街道', '人民路街道', '杜岭街道', '大石桥街道', '南阳路街道'],
  '鄂': ['大智街道', '一元街道', '车站街道', '四唯街道', '永清街道', '西马街道', '球场街道', '劳动街道', '二七街道', '新村街道', '丹水池街道', '台北街道', '花桥街道', '谌家矶街道', '后湖街道', '塔子湖街道', '百步亭花园', '民族街街道', '花楼街街道', '水塔街街道', '民权街街道', '满春街街道', '民意街街道', '新华街街道', '万松街街道', '唐家墩街街道', '北湖街街道', '前进街街道', '常青街街道', '汉兴街街道', '江汉经济开发区', '武汉中央商务区管理委员会', '古田街道', '韩家墩街道', '宗关街道', '汉水桥街道', '宝丰街道', '荣华街道', '汉中街道', '汉正街道', '六角亭街道', '长丰街道', '易家街道', '建桥街道', '晴川街道', '鹦鹉街道', '洲头街道', '五里墩街道', '琴断口街道', '江汉二桥街道'],
  '湘': ['文艺路街道', '朝阳街街道', '韭菜园街道', '五里牌街道', '火星街道', '马王堆街道', '东屯渡街道', '湘湖街道', '定王台街道', '荷花园街道', '东岸街道', '马坡岭街道', '东湖街道', '隆平高科技园', '坡子街街道', '城南路街道', '裕南街街道', '金盆岭街道', '新开铺街道', '青园街道', '桂花坪街道', '赤岭路街道', '文源街道', '先锋街道', '黑石铺街道', '大托铺街道', '暮云街道', '南托街道', '望月湖街道', '岳麓街道', '桔子洲街道', '银盆岭街道', '观沙岭街道', '望城坡街道', '西湖街道', '咸嘉湖街道', '望岳街道', '梅溪湖街道', '麓谷街道', '坪塘街道', '含浦街道', '天顶街道', '洋湖街道', '学士街道', '东方红街道', '莲花镇', '雨敞坪镇', '芙蓉北路街道', '东风路街道', '清水塘街道'],
  '粤': ['沙面街道', '岭南街道', '华林街道', '多宝街道', '昌华街道', '逢源街道', '龙津街道', '金花街道', '彩虹街道', '南源街道', '西村街道', '站前街道', '桥中街道', '白鹤洞街道', '冲口街道', '花地街道', '石围塘街道', '茶滘街道', '东漖街道', '海龙街道', '东沙街道', '中南街道', '洪桥街道', '北京街道', '六榕街道', '流花街道', '光塔街道', '人民街道', '东山街道', '农林街道', '梅花村街道', '黄花岗街道', '华乐街道', '建设街道', '大塘街道', '珠光街道', '大东街道', '白云街道', '登峰街道', '矿泉街道', '赤岗街道', '新港街道', '昌岗街道', '江南中街道', '滨江街道', '素社街道', '海幢街道', '南华西街道', '龙凤街道', '沙园街道'],
  '桂': ['民生街道', '朝阳街道', '兴东街道', '三塘镇', '五塘镇', '昆仑镇', '新竹街道', '中山街道', '建政街道', '南湖街道', '津头街道', '刘圩镇', '南阳镇', '伶俐镇', '长塘镇', '仙葫经济开发区', '青秀山', '福建园街道', '江南街道', '沙井街道', '那洪街道', '金凯街道', '吴圩镇', '苏圩镇', '延安镇', '江西镇', '经济技术开发区', '明阳工业园区', '衡阳街道', '北湖街道', '西乡塘街道', '安吉街道', '华强街道', '新阳街道', '上尧街道', '安宁街道', '石埠街道', '心圩街道', '金陵镇', '双定镇', '坛洛镇', '那龙矿务局', '高新技术开发区', '大沙田街道', '玉洞街道', '良庆镇', '那马镇', '那陈镇', '大塘镇', '南晓镇'],
  '琼': ['秀英街道', '海秀街道', '长流镇', '西秀镇', '海秀镇', '石山镇', '永兴镇', '东山镇', '中山街道', '滨海街道', '金贸街道', '大同街道', '海垦街道', '金宇街道', '城西镇', '龙桥镇', '新坡镇', '遵谭镇', '龙泉镇', '国兴街道', '府城街道', '滨江街道', '凤翔街道', '龙塘镇', '云龙镇', '红旗镇', '三门坡镇', '大坡镇', '甲子镇', '旧州镇', '省岭脚热带作物场', '海府街道', '蓝天街道', '博爱街道', '海甸街道', '人民街道', '白龙街道', '和平南街道', '白沙街道', '新埠街道', '灵山镇', '演丰镇', '三江镇', '大致坡镇', '海口桂林洋经济开发区（农场）', '罗牛山农场', '海棠区直辖村级区划', '吉阳区直辖村级区划', '天涯区直辖村级区划', '崖州区直辖村级区划'],
  '渝': ['高笋塘街道', '太白街道', '牌楼街道', '双河口街道', '龙都街道', '周家坝街道', '沙河街道', '钟鼓楼街道', '百安坝街道', '五桥街道', '陈家坝街道', '高峰街道', '天城街道', '九池街道', '小周镇', '大周镇', '新乡镇', '孙家镇', '龙沙镇', '响水镇', '武陵镇', '瀼渡镇', '甘宁镇', '熊家镇', '高梁镇', '李河镇', '分水镇', '余家镇', '后山镇', '弹子镇', '长岭镇', '新田镇', '白羊镇', '龙驹镇', '走马镇', '罗田镇', '太龙镇', '长滩镇', '太安镇', '白土镇', '郭村镇', '柱山乡', '铁峰乡', '溪口乡', '长坪乡', '燕山乡', '梨树乡', '普子乡', '地宝土家族乡', '恒合土家族乡'],
  '川': ['锦官驿街道', '东湖街道', '锦华路街道', '春熙路街道', '书院街街道', '牛市口街道', '沙河街道', '狮子山街道', '成龙路街道', '柳江街道', '三圣街道', '草市街街道', '西御河街道', '少城街道', '草堂街道', '府南街道', '光华街道', '金沙街道', '黄田坝街道', '苏坡街道', '文家街道', '蔡桥街道', '康河街道', '西安路街道', '西华街道', '荷花池街道', '驷马桥街道', '茶店子街道', '抚琴街道', '九里堤街道', '五块石街道', '营门口街道', '金泉街道', '沙河源街道', '天回镇街道', '凤凰山街道', '浆洗街街道', '望江路街道', '玉林街道', '火车南站街道', '晋阳街道', '红牌楼街道', '簇桥街道', '机投桥街道', '金花桥街道', '簇锦街道', '华兴街道', '芳草街街道', '肖家河街道', '石羊街道'],
  '黔': ['新华路街道', '西湖路街道', '水口寺街道', '中华南路街道', '河滨街道', '遵义路街道', '兴关路街道', '沙冲路街道', '望城街道', '太慈桥街道', '湘雅街道', '油榨街道', '中曹司街道', '二戈街道', '龙洞堡街道', '花果园街道', '小车河街道', '五里冲街道', '兰花都街道', '后巢乡', '云关乡', '小碧布依族苗族乡', '永乐乡', '大营路街道', '黔灵东路街道', '文昌阁街道', '盐务街街道', '普陀路街道', '八鸽岩街道', '毓秀路街道', '威清门街道', '市西河街道', '头桥街道', '三桥路街道', '马王街道', '金关街道', '茶园路街道', '杨惠街道', '渔安街道', '水东路街道', '黔灵镇', '贵筑街道', '阳光街道', '清溪街道', '溪北街道', '黄河路街道', '平桥街道', '小孟街道', '金筑街道', '党武街道'],
  '滇': ['华山街道', '护国街道', '大观街道', '龙翔街道', '丰宁街道', '莲华街道', '红云街道', '黑林铺街道', '普吉街道', '西翥街道', '昆明国家高新技术产业开发区', '拓东街道', '鼓楼街道', '东华街道', '联盟街道', '金辰街道', '青云街道', '龙泉街道', '茨坝街道', '双龙街道', '松华街道', '滇源街道', '阿子营街道', '关上街道', '太和街道', '吴井街道', '金马街道', '小板桥街道', '官渡街道', '矣六街道', '六甲街道', '大板桥街道', '阿拉街道', '长水街道', '小哨街道', '昆明经济技术开发区', '西苑街道', '马街街道', '金碧街道', '永昌街道', '前卫街道', '福海街道', '棕树营街道', '碧鸡街道', '海口街道', '团结街道', '昆明滇池国家旅游度假区', '铜都街道', '碧谷街道', '汤丹镇'],
  '藏': ['八廓街道', '吉日街道', '吉崩岗街道', '扎细街道', '公德林街道', '嘎玛贡桑街道', '两岛街道', '金珠西路街道', '蔡公堂街道', '夺底街道', '娘热街道', '纳金街道', '东嘎街道', '乃琼街道', '羊达街道', '柳梧街道', '古荣镇', '马镇', '德庆镇', '塔杰乡', '章多乡', '唐嘎乡', '雪乡', '帮堆乡', '甘丹曲果镇', '春堆乡', '松盘乡', '强嘎乡', '卡孜乡', '边交林乡', '江热夏乡', '阿朗乡', '唐古乡', '旁多乡', '当曲卡镇', '羊八井镇', '格达乡', '宁中乡', '公塘乡', '龙仁乡', '乌玛塘乡', '纳木湖乡', '塔荣镇', '吞巴镇', '麻江乡', '普松乡', '卡如乡', '尼木乡', '续迈乡', '帕古乡'],
  '陕': ['西一路街道', '长乐中路街道', '中山门街道', '韩森寨街道', '解放门街道', '自强路街道', '太华路街道', '长乐西路街道', '胡家庙街道', '南院门街道', '柏树林街道', '长乐坊街道', '东关南街街道', '太乙路街道', '文艺路街道', '长安路街道', '张家村街道', '青年路街道', '北院门街道', '北关街道', '红庙坡街道', '环城西路街道', '西关街道', '土门街道', '桃园路街道', '枣园街道', '纺织城街道', '十里铺街道', '红旗街道', '席王街道', '洪庆街道', '狄寨街道', '灞桥街道', '新筑街道', '新合街道', '张家堡街道', '三桥街道', '辛家庙街道', '徐家湾街道', '大明宫街道', '谭家街道', '草滩街道', '六村堡街道', '未央宫街道', '汉城街道', '未央湖街道', '建章路街道', '小寨路街道', '大雁塔街道', '长延堡街道'],
  '甘': ['酒泉路街道', '张掖路街道', '雁南街道', '临夏路街道', '雁北街道', '五泉街道', '白银路街道', '皋兰路街道', '广武门街道', '伏龙坪街道', '靖远路街道', '草场街街道', '火车站街道', '拱星墩街道', '东岗街道', '团结新村街道', '东岗西路街道', '铁路东村街道', '铁路西村街道', '渭源路街道', '盐场路街道', '嘉峪关路街道', '焦家湾街道', '青白石街道', '雁园街道', '高新区', '甘肃农垦集团', '甘肃监狱企业集团公司', '西园街道', '西湖街道', '建兰路街道', '敦煌路街道', '西站街道', '晏家坪街道', '龚家湾街道', '土门墩街道', '秀川街道', '阿干镇', '八里镇', '彭家坪镇', '西果园镇', '黄峪镇', '魏岭乡', '陈坪街道', '先锋路街道', '福利路街道', '西固城街道', '四季青街道', '临洮街街道', '西柳沟街道'],
  '青': ['东关大街街道', '清真巷街道', '大众街街道', '周家泉街道', '火车站街道', '八一路街道', '林家崖街道', '乐家湾镇', '韵家口镇', '东川工业园', '人民街街道', '南滩街道', '仓门街街道', '礼让街街道', '饮马街街道', '南川东路街道', '南川西路街道', '总寨镇', '南川工业园', '西关大街街道', '古城台街道', '虎台街道', '胜利路街道', '兴海路街道', '文汇路街道', '通海路街道', '彭家寨镇', '朝阳街道', '小桥大街街道', '马坊街道', '火车西站街道', '大堡子镇', '廿里铺镇', '生物科技产业园', '田家寨镇', '上新庄镇', '鲁沙尔镇', '甘河滩镇', '共和镇', '多巴镇', '拦隆口镇', '上五庄镇', '李家山镇', '西堡镇', '群加藏族乡', '土门关乡', '汉东回族乡', '大才回族乡', '海子沟乡', '甘河工业园'],
  '宁': ['凤凰北街街道', '解放西街街道', '文化街街道', '富宁街街道', '新华街街道', '玉皇阁北街街道', '前进街街道', '中山南街街道', '银古路街道', '胜利街街道', '丽景街街道', '星河街街道', '掌政镇', '大新镇', '通贵乡', '月牙湖乡', '西花园路街道', '北京西路街道', '文昌路街道', '朔方路街道', '宁华路街道', '贺兰山西路街道', '怀远路街道', '兴泾镇', '镇北堡镇', '满城北街街道', '黄河东路街道', '长城中路街道', '北京中路街道', '上海西路街道', '贺兰山中路街道', '良田镇', '丰登镇', '团结西路街道', '杨和镇', '李俊镇', '望远镇', '望洪镇', '闽宁镇', '胜利乡', '黄羊滩农场', '玉泉营农场', '富兴街街道', '习岗镇', '金贵镇', '立岗镇', '洪广镇', '常信乡', '南梁台子', '暖泉农场'],
  '新': ['燕儿窝街道', '胜利路街道', '团结路街道', '解放南路街道', '新华南路街道', '和平路街道', '解放北路街道', '幸福路街道', '东门街道', '新华北路街道', '青年路街道', '碱泉街道', '延安路街道', '红雁街道', '南草滩街道', '东泉路街道', '二道桥片区', '黑甲山片区', '大湾片区', '赛马场片区', '南湾街片区', '大巴扎片区', '长江路街道', '和田街街道', '扬子江路街道', '友好南路街道', '友好北路街道', '八一街道', '炉院街街道', '西山街道', '雅玛里克山街道', '红庙子街道', '长胜东街道', '长胜西街道', '长胜南街道', '火车南站街道', '仓房沟片区街道', '环卫路街道', '骑马山街道', '平顶山街道', '兵团农十二师一零四团', '兵团十二师西山农场', '北京路街道', '二工街道', '三工街道', '石油新村街道', '迎宾路街道', '喀什东路街道', '八家户街道', '银川路街道'],
};



// ─────────────────────────────────────────────
// 5. 七普年龄性别分层分布（2020年全国数据）
//    用于第四阶段：按年龄段 × 性别分层，抽 250 人
//    比例来源：七普公报第五号（年龄结构）
// ─────────────────────────────────────────────
const AGE_SEX_DIST = [
  // { group, maleRatio, femaleRatio } 比例加总 ≈ 1.0
  { group: '0-4岁',   male: 0.0274, female: 0.0238 },
  { group: '5-9岁',   male: 0.0334, female: 0.0285 },
  { group: '10-14岁', male: 0.0332, female: 0.0277 },
  { group: '15-19岁', male: 0.0305, female: 0.0265 },
  { group: '20-24岁', male: 0.0334, female: 0.0303 },
  { group: '25-29岁', male: 0.0388, female: 0.0358 },
  { group: '30-34岁', male: 0.0407, female: 0.0378 },
  { group: '35-39岁', male: 0.0366, female: 0.0344 },
  { group: '40-44岁', male: 0.0335, female: 0.0318 },
  { group: '45-49岁', male: 0.0386, female: 0.0369 },
  { group: '50-54岁', male: 0.0418, female: 0.0400 },
  { group: '55-59岁', male: 0.0388, female: 0.0376 },
  { group: '60-64岁', male: 0.0318, female: 0.0314 },
  { group: '65-69岁', male: 0.0256, female: 0.0257 },
  { group: '70-74岁', male: 0.0163, female: 0.0169 },
  { group: '75-79岁', male: 0.0102, female: 0.0115 },
  { group: '80+岁',   male: 0.0083, female: 0.0108 },
];
// 验证：所有比例之和 ≈ 1.0（男 0.4979 + 女 0.4874 = 0.9853，余量为性别比调整浮动）

// ─────────────────────────────────────────────
// 6. 工具函数
// ─────────────────────────────────────────────
const DataHelper = {
  getRegions() { return REGIONS; },
  getProvince(abbr) { return PROVINCES[abbr]; },
  getProvincesByRegion(regionId) {
    return Object.entries(PROVINCES)
      .filter(([, p]) => p.region === regionId)
      .map(([abbr, p]) => ({ abbr, ...p }));
  },
  getCities(abbr) { return (CITIES[abbr] || []).map((c, i) => ({ ...c, id: `${abbr}_${i}` })); },
  /**
   * 获取街道/乡镇备选池
   * @param {string} cityType  城市类型：capital / city / county
   * @param {string} provAbbr  省份缩写（如 '闽'），county 类型时优先使用该省真实数据
   */
  getStreets(cityType, provAbbr = '') {
    // county 级别优先用各省真实数据
    if (cityType === 'county' && provAbbr && COUNTY_STREETS[provAbbr]) {
      return COUNTY_STREETS[provAbbr];
    }
    return [...(STREET_TEMPLATES[cityType] || STREET_TEMPLATES.city)];
  },
  getAgeSexDist() { return AGE_SEX_DIST; },
  /**
   * 根据七普年龄性别分布，为一个街道生成 250 人抽样名单
   * @param {string} streetName
   * @param {number} total 目标人数，默认 250
   */
  generate250People(streetName, total = 250) {
    const people = [];
    let id = 1;
    // 按比例分配，最后凑满 total
    const slots = AGE_SEX_DIST.map(d => ({
      group: d.group,
      maleCnt: Math.round(d.male * total),
      femaleCnt: Math.round(d.female * total),
    }));
    // 修正总数
    let sum = slots.reduce((s, r) => s + r.maleCnt + r.femaleCnt, 0);
    let diff = total - sum;
    if (diff > 0) slots[slots.length - 1].maleCnt += diff;
    if (diff < 0) slots[0].maleCnt = Math.max(0, slots[0].maleCnt + diff);

    for (const slot of slots) {
      for (let m = 0; m < slot.maleCnt; m++) {
        people.push({ id: id++, street: streetName, ageGroup: slot.group, sex: '男' });
      }
      for (let f = 0; f < slot.femaleCnt; f++) {
        people.push({ id: id++, street: streetName, ageGroup: slot.group, sex: '女' });
      }
    }
    return people.slice(0, total);
  },
};
